name: Run Python Script on Push to Source Folder

on:
  push:
    paths:
      - "source/**"

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-python@v5
    with:
      python-version: "3.12"
  - run: python countImages.py
