name: Run Python Script on Push to Source Folder

on:
  push:
    paths:
      - "source/**"

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run the Python Script countImages.py
        run: python countImages.py
